name: Build WebP Converter

on:
  release:
    types: [created]
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build application
      run: |
        python build.py
        
    - name: Create DMG
      run: |
        brew install create-dmg
        create-dmg \
          --volname "WebP Converter" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "WebP Converter.app" 200 190 \
          --hide-extension "WebP Converter.app" \
          --app-drop-link 600 185 \
          "WebP Converter.dmg" \
          "dist/WebP Converter.app"
        
    - name: Upload DMG
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./WebP Converter.dmg
        asset_name: WebP Converter.dmg
        asset_content_type: application/octet-stream